In [1]:
import pandas as pd
df=pd.read_csv('preprocessed.csv')
df

,qty_slash_url,length_url,qty_dot_domain,qty_dot_directory,qty_hyphen_directory,qty_underline_directory,asn_ip,time_domain_activation,time_domain_expiration,ttl_hostname
0,-0.120998,-0.268311,0.239519,1.731591,0.641758,0.842368,2.020066,-1.113859,-0.887213,-0.676608
1,1.115652,2.151740,0.239519,2.371476,0.641758,0.842368,0.613451,-0.923324,-0.365891,0.585543
2,-0.120998,-0.812142,0.239519,0.451819,0.641758,0.842368,-1.162531,-1.113859,-0.887213,-0.720831
3,2.352302,2.151740,0.239519,2.371476,0.641758,3.402833,-0.271188,-1.113859,-0.887213,-0.764177
4,-0.739323,-0.594610,0.239519,-0.827953,-0.825461,-0.864608,1.625189,1.185371,0.172694,-0.281821
...,...,...,...,...,...,...,...,...,...,...
88642,-0.739323,-0.377077,1.862500,-0.827953,-0.825461,-0.864608,-0.946968,0.696222,0.269363,-0.281821
88643,-0.739323,0.221138,0.239519,-0.827953,-0.825461,-0.864608,0.072100,0.544122,0.604252,-0.720539
88644,2.352302,2.151740,-1.383462,1.731591,2.108977,0.842368,2.390597,-0.507761,1.574394,1.293533
88645,-0.120998,-0.105161,0.239519,0.451819,0.641758,0.842368,1.270197,-1.113859,-0.887213,-0.799204
88646,-0.739323,-0.757759,0.239519,-0.827953,-0.825461,-0.864608,1.285140,-1.014978,-0.662803,-0.763155

In [1]:
import pandas as pd
df=pd.read_csv('train.csv')
df

,qty_dot_url,qty_hyphen_url,qty_underline_url,qty_slash_url,qty_equal_url,qty_at_url,qty_and_url,qty_tld_url,length_url,qty_dot_domain,...,tld_present_params,qty_params,email_in_url,domain_spf,asn_ip,time_domain_activation,time_domain_expiration,qty_ip_resolved,ttl_hostname,phishing
0,2,0,0,0,0,0,0,1,20,2,...,-1,-1,0,0,27647,6428,145,1,591,0
1,6,1,0,6,1,1,0,3,74,3,...,1,1,1,0,11664,-1,-1,1,21596,1
2,2,0,0,0,0,0,0,1,24,2,...,-1,-1,0,0,27647,5601,1703,1,7198,0
3,2,0,0,0,0,0,0,1,13,2,...,-1,-1,0,0,26496,-1,-1,1,590,0
4,1,0,0,1,0,0,0,1,17,1,...,-1,-1,0,0,16509,-1,-1,6,1002,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62047,2,0,0,0,0,0,0,1,21,2,...,-1,-1,0,0,13335,6279,1025,1,300,0
62048,3,0,0,1,0,0,0,1,25,2,...,-1,-1,0,0,44476,-1,-1,1,3592,1
62049,1,1,2,6,0,0,0,1,59,1,...,-1,-1,0,-1,13576,3519,132,1,9221,1
62050,2,0,0,0,0,0,0,1,14,2,...,-1,-1,0,0,26347,3330,716,1,14398,0
62051,2,0,0,0,0,0,0,1,17,2,...,-1,-1,0,0,29854,4701,46,1,86389,0